api=http://127.0.0.1:8080/api/predictLb
api_key=pk_live_nlKn4wYAMKWir4nQiCbzrGE3tvVJUKa4

Performance=yes
Throughtput=no
Overhead=yes
Tolerant=yes
MigrationTime=yes
ResponseTime=yes
RessourceUtilization=no
Scalability=yes
PowerSaving=no

toleranceMax=2
deadline=1000
tolerance=100
timeMax=10000
throughputMax=0.00002
responseTimeMAX=0.4
ressourceCpuMax=80
